Add setup script, update README with setup instructions

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,34 +1,111 @@
-#!/usr/bin/env ruby
-require 'pathname'
-require 'fileutils'
-include FileUtils
+#!/bin/bash
+red=`tput setaf 1`
+green=`tput setaf 2`
+bold=`tput bold`
+reset=`tput sgr0`
 
-# path to your application root.
-APP_ROOT = Pathname.new File.expand_path('../../', __FILE__)
+function log_right {
+    LEFT="$1"
+    RIGHT="$2"
+    COLOR=$3
+    RESET=${reset}
+    let COLS=$(tput cols)-${#LEFT}+${#COLOR}+${#RESET}
+    printf "%${COLS}s\n" "$COLOR$RIGHT$RESET"
+}
 
-def system!(*args)
-  system(*args) || abort("\n== Command #{args} failed ==")
-end
+function check_install {
+    read -p "$1 is not installed. Install now? [y/n]: " -n 1 -r
+    echo
+    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
+        exit
+    fi
+}
 
-chdir APP_ROOT do
-  # This script is a starting point to setup your application.
-  # Add necessary setup steps to this file.
+MSG="Checking operating system..."
+echo -n $MSG
+os=`uname -s`
+if [ $os == "Darwin" ]; then
+    log_right "$MSG" "Mac OS X" $bold
+    MSG="Verifying Homebrew is installed..."
+    echo -n $MSG
+    which brew &> /dev/null
+    if [ $? -eq 0 ]; then
+        log_right "$MSG" "Ok" $green
+        MSG="Verifying Homebrew is up to date..."
+        echo -n $MSG
+        brew update &> /dev/null
+        if [ $? -eq 0 ]; then
+            log_right "$MSG" "Ok" $green
+        else
+            log_right "$MSG" "Error" $green
+            echo "${red}There was a problem updating Homebrew. Please ensure the following command completes successfully:${reset}"
+            echo -e "\t${bold}brew update${reset}"
+            exit 1
+        fi
+    else
+        log_right "$MSG" "Not installed" $red
+        check_install "Homebrew"
+        echo "Installing Homebrew..."
+        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+        if [ $? -ne 0 ]; then
+            echo "${red}There was a problem installing Homebrew. Please ensure the following command completes successfully:${reset}"
+            echo -e "\t${bold}ruby -e \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)\"${reset}"
+            exit 1
+        fi
+    fi
+else
+    # Currently only support Macs; will update over time
+    log_right "$MSG" "Could not detect operating system" $red
+    echo "Please see the GitHub wiki for instructions on installing ImageMagick on your system."
+fi
 
-  puts '== Installing dependencies =='
-  system! 'gem install bundler --conservative'
-  system('bundle check') || system!('bundle install')
+MSG="Verifying rvm is installed..."
+echo -n $MSG
+which rvm &> /dev/null
+if [ $? -eq 0 ]; then
+    log_right "$MSG" "Ok" $green
+else
+    log_right "$MSG" "Not installed" $red
+    check_install "rvm"
+    MSG="Installing rvm..."
+    echo -n $MSG
+    \curl -sSL https://get.rvm.io | bash
+    if [ $? -ne 0 ]; then
+        exit
+    fi
+    log_right "$MSG" "rvm successfully installed." $green
+    # Need to reload bash_profile to rvm to PATH
+    source ~/.bash_profile
+fi
 
-  # puts "\n== Copying sample files =="
-  # unless File.exist?('config/database.yml')
-  #   cp 'config/database.yml.sample', 'config/database.yml'
-  # end
+echo "Installing correct ruby version..."
+rvm install `cat .ruby-version`
+if [ $? -ne 0 ]; then
+    exit
+fi
 
-  puts "\n== Preparing database =="
-  system! 'bin/rails db:setup'
+rvm use `cat .ruby-version`
 
-  puts "\n== Removing old logs and tempfiles =="
-  system! 'bin/rails log:clear tmp:clear'
+echo "Installing Bundler..."
+gem install bundler
+if [ $? -ne 0 ]; then
+    exit
+fi
 
-  puts "\n== Restarting application server =="
-  system! 'bin/rails restart'
-end
+echo "Installing third-party gems..."
+bundle install --without production
+if [ $? -ne 0 ]; then
+    exit
+fi
+
+echo "Installing git hooks..."
+overcommit --install
+if [ $? -ne 0 ]; then
+    exit
+fi
+
+echo "Setting up development database..."
+rake db:setup
+if [ $? -ne 0 ]; then
+    exit
+fi
